### ISSUE TITLE
Access Problems using METABOLIC-G

### ISSUE THREAD

**Issue by pjmramond** [marbits-icm/marbits-public#104]
Hello there
I see from my script's outputs and logs (this was run last week, pre-apagòn) that METABOLIC-G cannot access or find various files.

See this error message:
```
readline() on closed filehandle IN at /home/apps/metabolic/4.0_6a598f9/METABOLIC-G.pl line 1142.
readline() on closed filehandle IN at /home/apps/metabolic/4.0_6a598f9/METABOLIC-G.pl line 1142.
readline() on closed filehandle IN at /home/apps/metabolic/4.0_6a598f9/METABOLIC-G.pl line 1159.
readline() on closed filehandle IN at /home/apps/metabolic/4.0_6a598f9/METABOLIC-G.pl line 1159.
[2025-04-21 06:22:19] The hmmsearch is running with 20 cpu threads...

Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc1.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc1.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc1.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc1.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster1.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster1.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster1.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster1.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster2.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster2.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster2.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster2.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster3.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster3.hmm not found (nor an .h3m binary of it)
Error: File existence/permissions problem in trying to open HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster3.hmm.
HMM file /home/apps/metabolic/4.0_6a598f9/METABOLIC_hmm_db/Cyc2_repCluster3.hmm not found (nor an .h3m binary of it)
```

Just for reference this is my script:
```
#!/bin/bash
#SBATCH --job-name=metabolic
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --output=logs/metabolicgc.log_%A_%a.out
#SBATCH --error=logs/metabolicgc.log_%A_%a.err
#SBATCH --mem=700G
 
# load modules
module load metabolic
source activate

# save directories and samples names
#sp=$(cat eukaryotes/samples2 | awk "NR==$SLURM_ARRAY_TASK_ID" )
input=/home/pramond/smart/SOLA/gene_catalogue/10_metabolic
output=../gene_catalogue/11_metabolic_results
rm -r $ouput

# run commands
METABOLIC-G.pl -t 20 -in $input -o $output
```

Please tell me if the error comes from my side, otherwise thanks for the support!
Best
Pierre

**Comment by pablo-icm** [comment]
Hi @franlat, could you take a look at this?

**Comment by franlat** [comment]
I'm on it. Looks like all the DB links are broken, including dbcan and kofam. Since METABOLIC hasn't been updated since 2021 it looks like re-downloading them will be easy.

**Comment by franlat** [comment]
Ok! It should be fixed now. Can you try again, please? Old symlinks pointed to already downloaded version of databases, but since those are not accessible, I linked them to the version available within the METABOLIC GitHub. 

Maybe I missed changing some permissions, so I will let this open until we can test whether it runs or not.

**Comment by pjmramond** [comment]
Thanks for the support, I launched a job using METABOLIC.
I'll give you an update soon as it runs!

**Comment by pjmramond** [comment]
Hello there,
METABOLIC is still crashing with the same error message about permissions:

![Image](https://github.com/user-attachments/assets/b7f6c0b6-73d9-4b69-be8a-47d988de0be3)

**Comment by pjmramond** [comment]
Wait, maybe this is related to #122 ?

**Comment by franlat** [comment]
No, the problem is that all the symlinks I modified to the new location are pointing to the old one (broken lustre) again, I guess it happened during the mount of the new `/home` disks... 🤕 🤦🏻 

I will have to pause this until the new disks are mounted 100%, and everything is alright. Then I will transfer the new files directly, without doing symlinks.

**Comment by pjmramond** [comment]
Right so no METABOLIC until further notice?

**Comment by franlat** [comment]
Yep. I could change them again, but it will probably revert to the old links anyway. So it is safer to wait until I have the green light that everything is mounted correctly.

**Comment by franlat** [comment]
Ok! Since the new quotas are installed for everyone, I fixed the links again. They "might" broke again in the future, if we have to move the METABOLIC database files again (since they are symlinks), but in the meantime, it should be fixed. 

Let me know if it works!

**Comment by pablo-icm** [comment]
Hi, homes shouldn't change anymore. I think it is safe now. @franlat must have edited it in the old homes and disappeared when I mounted the new ones (I only backed up the users' homes, not the apps dir)

**Comment by pablo-icm** [comment]
by the way, @franlat, I have grouped all app databases (including METABOLIC's) in `/home/apps/app-dbs` now that we have extra room in `/home`

**Comment by franlat** [comment]
Perfect! I modified the symlinks again, now the pont to the new location
