### ISSUE TITLE
[General Issue] cp: error writing ‘...’: Disk quota exceeded

### ISSUE THREAD

**Issue by aleixop** [marbits-icm/marbits-public#88]
### 🏷️ Issue Category

💣 panic

### 📝 Issue Description

```markdown
Hi, I am trying to copy some files from cold02 to smart for computing, but I am getting this error. I deleted  lots of big files and I don't think I have a ton of files there. Anyone with the same issue?
```

**Comment by onadeulofeu** [comment]
I get the same error...

**Comment by paubach711** [comment]
Hello Juanlu the new HPC admin added 1Tb quota to fix the smart-lustre disk storage I think he forgot to send a mail to smart-users list.

**Comment by sandrarcr** [comment]
Hi Pau, 

Thank you. Does this mean the issue is resolved just for today? Thanks for clarifying.

**Comment by paubach711** [comment]
Well its not fixed yet, adding these quotas did more damage rather than help, i hope that in the next weeks we are able to fix everyone issues regarding smart

**Comment by aleixop** [comment]
Hi Pau,

Thanks for the information. Indeed, being informed about this would have been nice...

**Comment by paubach711** [comment]
Yeah sorry about that...
I knew about the quotas but i didn't know that they implemented this today

**Comment by onadeulofeu** [comment]
Okey, thank you for the information, will you let us know when it is fixed?

**Comment by pablo-icm** [comment]
Yes, it seems that 1 Terabyte quotas were enforced yesterday in `/mnt/smart`. If you can get below that figure you'll be able to write there again. So sorry for the inconvenience

**Comment by paubach711** [comment]
From ICM HPC admin

```
Bon dia,

qui necessiti ampliar la seva quota al lustre de SMART per llençar nous
jobs a qualsevol dels HPC (SMART, GAIA i LMARBITS), sis-plau poseu-vos
en contacte amb mi. Preferiblement enviant un mail a [smart@icm.csic.es](mailto:smart@icm.csic.es)
que estem fent servir com a sistema de tickets pel Servei de Computació

Gràcies
```

**Comment by pjmramond** [comment]
Does this explain why I can't ```scp``` data from local to _marbits_?

**Comment by paubach711** [comment]
Are you doing ```scp``` into ```/mnt/smart```?

**Comment by pjmramond** [comment]
Yes to ```/mnt/smart````

**Comment by paubach711** [comment]
Then thats why you can't do ```scp```

**Comment by pjmramond** [comment]
To be clear, any usage (writing, copying, computation) in ```/mnt/smart``` is not working right?

**Comment by pjmramond** [comment]
I don't honestly see how I could lower my memory usage to 1TB in ```/mnt/smart/```. I am processing raw data that is already 4.8TB. I do think that some other users are in the same case. Handling meta genomics data is simply not feasible like this. Especially when there is no other option ```cold02``` being not usable for computation (and very slow for transferring files from smart).

Enforcing this quota without consulting users is quite bold, to say the least.

**Comment by franlat** [comment]
Hi Pierre! 

You can ask for more space by filling the form that Pablo mentioned in https://github.com/marbits-icm/marbits-public/discussions/94#discussion-8192202

Also, he mounted `cold02` in the 10G pipe a few hours ago, so it should be faster now https://github.com/marbits-icm/marbits-public/issues/90#issuecomment-2797021775. 

If you want to know how much space your user is taking, you can do: `lfs quota -u flatorre /mnt/smart`
